name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    name: build the project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: install dependencies
      run: npm install 

    - name: build the project
      run: npm run build 
    
    - name: test project
      run: npm run test
    
    - name: cd examples
      run: cd example 
    
    - name: install dependencies (example)
      run: npm install
    
    - name: install dependencies (example)
      run: npm install 

    - name: build the project (example)
      run: npm run build 
    
    - name: test project (example)
      run: npm run test
